### ISSUE TITLE
How to enable damping?

### ISSUE THREAD

**Issue by quacrobat** [vanruesc/delta-controls#3]
Hello, do these controls have camera movement damping possibility like OrbitControls? 
Thanks

**Comment by vanruesc** [comment]
Damping is not supported [yet](https://github.com/vanruesc/spatial-controls/blob/1e29623dc9d561f0b4f46c3258cd5de6d0eba7ff/src/managers/RotationManager.ts#L317).

I've been keeping the following articles bookmarked for when I eventually get around to implementing damping:
http://www.rorydriscoll.com/2016/03/07/frame-rate-independent-damping-using-lerp/
https://answers.unity.com/questions/215553/smoother-camera-movement.html
https://github.com/Unity-Technologies/UnityCsReference/blob/61f92bd79ae862c4465d35270f9d1d57befd1761/Runtime/Export/Math/Mathf.cs#L303-L331

Let me know if there are any other references that I should consider.

**Comment by vanruesc** [comment]
Implemented damping in `spatial-controls@4.3.0`.
