### ISSUE TITLE
How to block axis-movement?

### ISSUE THREAD

**Issue by Mateo150** [vanruesc/delta-controls#5]
Hi Vanruesc,

First to all, thanks for this helpful controls.
Now, I'm trying to implement this as a first person camera controls, but when I try to "walk" forward while I'm looking the down, the camera goes down and ends up getting inside the floor.
For example, in Cannon-es, we can apply something called "factor" to the "movement" as a vector3: [LinearFactor](https://pmndrs.github.io/cannon-es/docs/classes/Body.html#linearFactor)
This concept applied to spatial, `settings.translation.factor.set(1,0,1)` wich means the movement is blocked in Y axis... giving the effect I'm trying to reach. Is like 'Sensitivity' here but giving the option to be more especific.
Idk, this can be an improvement for Sensitivity.

Is that possible here?

**Comment by vanruesc** [comment]
Thanks for the suggestion!

I've added `settings.translation.axisWeights` in `spatial-controls@6.1.0` which should do the trick.

**Comment by vanruesc** [comment]
Related: #4
